/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorRefDTO } from '../user/authorRefDTO';
import { SandboxDefinitionRefDto } from '../sandbox-definition/sandbox-definition-ref-dto';
import {ViewGroupDTO} from "./viewGroupDTO";
import {ViewGroupCreateDTO} from "./viewGroupCreateDTO";


/**
 * Training Definition to create.
 */
export interface TrainingDefinitionCreateDTO {
    author_logins?: Array<string>;
    td_view_group: ViewGroupCreateDTO;
    description?: string;
    outcomes?: Array<string>;
    prerequisities?: Array<string>;
    sandbox_definition_ref_id: number;
    show_stepper_bar?: boolean;
    state?: TrainingDefinitionCreateDTO.StateEnum;
    title?: string;
}

export class TrainingDefinitionCreateDTOClass implements  TrainingDefinitionCreateDTO {
  author_logins: Array<string>;
  td_view_group: ViewGroupCreateDTO;
  description: string;
  outcomes: Array<string>;
  prerequisities: Array<string>;
  sandbox_definition_ref_id: number;
  show_stepper_bar: boolean;
  state: TrainingDefinitionCreateDTO.StateEnum;
  title: string;
}

export namespace TrainingDefinitionCreateDTO {
    export type StateEnum = 'PRIVATED' | 'RELEASED' | 'ARCHIVED' | 'UNRELEASED';
    export const StateEnum = {
        PRIVATED: 'PRIVATED' as StateEnum,
        RELEASED: 'RELEASED' as StateEnum,
        ARCHIVED: 'ARCHIVED' as StateEnum,
        UNRELEASED: 'UNRELEASED' as StateEnum
    }
}
