/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostHookDTO } from '../training-definition/postHookDTO';
import { PreHookDTO } from '../training-definition/preHookDTO';


/**
 * .
 */
export interface AbstractLevelDTO {
    id?: number;
    max_score?: number;
    estimated_duration: number;
    order: number;
    snapshot_hook?: any;
    title?: string;
    level_type: AbstractLevelDTO.LevelTypeEnum;
}

export namespace AbstractLevelDTO {
  export type LevelTypeEnum = 'INFO_LEVEL' | 'ASSESSMENT_LEVEL' | 'GAME_LEVEL';
  export const LevelTypeEnum = {
    INFO: 'INFO_LEVEL' as LevelTypeEnum,
    ASSESSMENT: 'ASSESSMENT_LEVEL' as LevelTypeEnum,
    GAME: 'GAME_LEVEL' as LevelTypeEnum
  }
}
