/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostHookDTO } from './postHookDTO';
import { PreHookDTO } from './preHookDTO';


/**
 * .
 */
export interface AbstractLevelDTO {
    id?: number;
    maxScore?: number;
    nextLevel?: number;
    postHook?: PostHookDTO;
    preHook?: PreHookDTO;
    title?: string;
}
