/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostHookDTO } from './postHookDTO';
import { PreHookDTO } from './preHookDTO';

/**
 * .
 */
export interface AbstractLevelDTO {
    id?: number;
    maxScore?: number;
    nextLevel?: number;
    postHook?: PostHookDTO;
    preHook?: PreHookDTO;
    title?: string;
    levelType: string;
}

export namespace AbstractLevelDTO {
  export type LevelTypeEnum = 'GAME' | 'INFO' | 'ASSESSMENT';
  export const LevelTypeEnum = {
    GAME: 'GAME' as LevelTypeEnum,
    INFO: 'INFO' as LevelTypeEnum,
    ASSESSMENT: 'ASSESSMENT' as LevelTypeEnum,
  }
}
