/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostHookDTO } from './postHookDTO';
import { PreHookDTO } from './preHookDTO';


/**
 * .
 */
export interface AbstractLevelDTO {
    id?: number;
    max_score?: number;
    next_level?: number;
    post_hook?: PostHookDTO;
    pre_hook?: PreHookDTO;
    title?: string;
    level_type: AbstractLevelDTO.LevelTypeEnum;
}

export namespace AbstractLevelDTO {
  export type LevelTypeEnum = 'INFO' | 'ASSESSMENT' | 'GAME';
  export const LevelTypeEnum = {
    INFO: 'INFO' as LevelTypeEnum,
    ASSESSMENT: 'ASSESSMENT' as LevelTypeEnum,
    GAME: 'GAME' as LevelTypeEnum

  }
}
