/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * .
 */
export interface AccessedTrainingRunDTO {
    currentLevelOrder?: number;
    id?: number;
    numberOfLevels?: number;
    possibleAction?: AccessedTrainingRunDTO.PossibleActionEnum;
    title?: string;
    trainingInstanceEndDate?: Date;
    trainingInstanceStartDate?: Date;
}
export namespace AccessedTrainingRunDTO {
    export type PossibleActionEnum = 'TRY_AGAIN' | 'RESULTS';
    export const PossibleActionEnum = {
        TRYAGAIN: 'TRY_AGAIN' as PossibleActionEnum,
        RESULTS: 'RESULTS' as PossibleActionEnum
    }
}
