/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractLevelDTO } from './abstractLevelDTO';
import { BasicLevelInfoDTO } from './basicLevelInfoDTO';


/**
 * .
 */
export interface AccessTrainingRunDTO {
    abstractLevelDto?: AbstractLevelDTO;
    infoAboutLevels?: Array<BasicLevelInfoDTO>;
}
