/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Assessment Level to update.
 */
export interface AssessmentLevelUpdateDTO {
    /**
     * ID of assessment level to update. Have not be null.
     */
    id?: number;
    /**
     * Instructions of assessment level to update.
     */
    instructions?: string;
    /**
     * Maximum score of assessment level to update. Have to be filled in range from 0 to 100.
     */
    max_score?: number;
    /**
     * Questions of assessment level to update.
     */
    questions?: string;
    /**
     * Title of assessment level to update. Have to be filled.
     */
    title?: string;
    /**
     * Type of assessment level to update.
     */
    type?: AssessmentLevelUpdateDTO.TypeEnum;
}
export namespace AssessmentLevelUpdateDTO {
    export type TypeEnum = 'TEST' | 'QUESTIONNAIRE';
    export const TypeEnum = {
        TEST: 'TEST' as TypeEnum,
        QUESTIONNAIRE: 'QUESTIONNAIRE' as TypeEnum
    }
}
