/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import {AbstractLevelDTO} from "./abstractLevelDTO";
import {PreHookDTO} from "./preHookDTO";
import {PostHookDTO} from "./postHookDTO";

/**
 * Assessment Level to update.
 */
export interface AssessmentLevelUpdateDTO extends AbstractLevelDTO {
    instructions?: string;
    questions?: string;
    type?: AssessmentLevelUpdateDTO.TypeEnum;
}
export namespace AssessmentLevelUpdateDTO {
    export type TypeEnum = 'TEST' | 'QUESTIONNAIRE';
    export const TypeEnum = {
        TEST: 'TEST' as TypeEnum,
        QUESTIONNAIRE: 'QUESTIONNAIRE' as TypeEnum
    }
}

export class AssessmentLevelUpdateDTOClass implements AssessmentLevelUpdateDTO {
  id: number;
  instructions: string;
  level_type: AbstractLevelDTO.LevelTypeEnum;
  max_score: number;
  next_level: number;
  post_hook: PostHookDTO;
  pre_hook: PreHookDTO;
  questions: string;
  title: string;
  type: AssessmentLevelUpdateDTO.TypeEnum;

}
