/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Assessment Level to update.
 */
export interface AssessmentLevelUpdateDTO {
    id?: number;
    instructions?: string;
    maxScore?: number;
    nextLevel?: number;
    questions?: string;
    title?: string;
    type?: AssessmentLevelUpdateDTO.TypeEnum;
}
export namespace AssessmentLevelUpdateDTO {
    export type TypeEnum = 'TEST' | 'QUESTIONNAIRE';
    export const TypeEnum = {
        TEST: 'TEST' as TypeEnum,
        QUESTIONNAIRE: 'QUESTIONNAIRE' as TypeEnum
    }
}
