/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Game Level to update.
 */
export interface GameLevelUpdateDTO {
    attachments?: Array<string>;
    content?: string;
    estimatedDuration?: number;
    flag?: string;
    id?: number;
    incorrectFlagLimit?: number;
    maxScore?: number;
    nextLevel?: number;
    solution?: string;
    solutionPenalized?: boolean;
    title?: string;
}

export class GameLevelUpdateDTO implements GameLevelUpdateDTO {

}
