/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HintDTO } from './hintDTO';


/**
 * Game Level to update.
 */
export interface GameLevelUpdateDTO {
    attachments?: Array<string>;
    content?: string;
    estimated_duration?: number;
    flag?: string;
    hints?: Array<HintDTO>;
    id?: number;
    incorrect_flag_limit?: number;
    max_score?: number;
    solution?: string;
    solution_penalized?: boolean;
    title?: string;
}
