/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface HintDTO {
    content?: string;
    hint_penalty?: number;
    id?: number;
    title?: string;
}

export class HintDTOClass implements HintDTO {
  content: string;
  hint_penalty: number;
  id: number;
  title: string;
}
