/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Info Level to update.
 */
export interface InfoLevelUpdateDTO {
    content?: string;
    id?: number;
    maxScore?: number;
    nextLevel?: number;
    title?: string;
}

export class InfoLevelUpdateDTO implements InfoLevelUpdateDTO {

}
