/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import {AbstractLevelDTO} from "./abstractLevelDTO";
import {PostHookDTO} from "./postHookDTO";
import {PreHookDTO} from "./preHookDTO";

/**
 * Info Level to update.
 */
export interface InfoLevelUpdateDTO extends AbstractLevelDTO{
    content?: string;
    id?: number;
    title?: string;
}

export class InfoLevelUpdateDTOClass implements InfoLevelUpdateDTO {
  level_type: AbstractLevelDTO.LevelTypeEnum;
  max_score: number;
  next_level: number;
  order: number;
  post_hook: PostHookDTO;
  pre_hook: PreHookDTO;
  content: string;
  id: number;
  title: string;
}
