/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Pagination {
    /**
     * Page number.
     */
    number?: number;
    /**
     * Number of elements in page.
     */
    numberOfElements?: number;
    /**
     * Page size.
     */
    size?: number;
    /**
     * Total number of elements in this resource (in all Pages).
     */
    totalElements?: number;
    /**
     * Total number of pages.
     */
    totalPages?: number;
}
