/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorRefDTO } from './authorRefDTO';
import { SandboxDefinitionRefDTO } from './sandboxDefinitionRefDTO';
import {ViewGroupDTO} from "./viewGroupDTO";
import {ViewGroupUpdateDTO} from "./viewGroupUpdateDTO";


/**
 * Training Definition to update.
 */
export interface TrainingDefinitionUpdateDTO {
    author_logins?: Array<string>;
    td_view_group: ViewGroupUpdateDTO
    description?: string;
    id?: number;
    outcomes?: Array<string>;
    prerequisities?: Array<string>;
    sandbox_definition_ref_id?: number;
    show_stepper_bar?: boolean;
    state?: TrainingDefinitionUpdateDTO.StateEnum;
    title?: string;
}

export class TrainingDefinitionUpdateDTOClass implements TrainingDefinitionUpdateDTO {
  author_logins?: Array<string>;
  td_view_group: ViewGroupUpdateDTO;
  description: string;
  id: number;
  outcomes: Array<string>;
  prerequisities: Array<string>;
  sandbox_definition_ref_id?: number;
  show_stepper_bar: boolean;
  state: TrainingDefinitionUpdateDTO.StateEnum;
  title: string;
}

export namespace TrainingDefinitionUpdateDTO {
    export type StateEnum = 'PRIVATED' | 'RELEASED' | 'ARCHIVED' | 'UNRELEASED';
    export const StateEnum = {
        PRIVATED: 'PRIVATED' as StateEnum,
        RELEASED: 'RELEASED' as StateEnum,
        ARCHIVED: 'ARCHIVED' as StateEnum,
        UNRELEASED: 'UNRELEASED' as StateEnum
    }
}
