/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractLevelDTO } from './abstractLevelDTO';
import { SandboxInstanceRefDTO } from './sandboxInstanceRefDTO';
import { TrainingInstanceDTO } from './trainingInstanceDTO';
import {UserRefDTO} from "./userRefDTO";


/**
 * .
 */
export interface TrainingRunDTO {
    current_level?: AbstractLevelDTO;
    end_time?: Date;
    event_log_reference?: string;
    id?: number;
    sandbox_instance_ref?: SandboxInstanceRefDTO;
    participant_ref: UserRefDTO;
    start_time?: Date;
    state?: TrainingRunDTO.StateEnum;
    training_instance?: TrainingInstanceDTO;
}
export namespace TrainingRunDTO {
    export type StateEnum = 'NEW' | 'ALLOCATED' | 'READY' | 'ARCHIVED';
    export const StateEnum = {
        NEW: 'NEW' as StateEnum,
        ALLOCATED: 'ALLOCATED' as StateEnum,
        READY: 'READY' as StateEnum,
        ARCHIVED: 'ARCHIVED' as StateEnum
    }
}
