/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainingDefinitionDTO } from './trainingDefinitionDTO';
import { UserRefDTO } from './userRefDTO';


/**
 * Training Instance to update.
 */
export interface TrainingInstanceUpdateDTO {
    end_time?: string;
    id?: number;
  access_token?: string;
    org_ids?: Array<number>;
    pool_size?: number;
    start_time?: string;
    title?: string;
    training_definition_id?: number;
}

export class TrainingInstanceUpdateDTOClass implements TrainingInstanceUpdateDTO {
  end_time: string;
  id: number;
  access_token: string;
  org_ids?: Array<number>;
  pool_size: number;
  start_time: string;
  title: string;
  training_definition_id: number;
}
