/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorRefDTO } from './authorRefDTO';
import { BasicLevelInfoDTO } from './basicLevelInfoDTO';
import { SandboxDefinitionRefDTO } from './sandboxDefinitionRefDTO';


/**
 * .
 */
export interface TrainingDefinitionDTO {
    authorRefDto?: Array<AuthorRefDTO>;
    basicLevelInfoDtos?: Array<BasicLevelInfoDTO>;
    description?: string;
    id?: number;
    outcomes?: Array<string>;
    prerequisities?: Array<string>;
    sandBoxDefinitionRefDto?: SandboxDefinitionRefDTO;
    startingLevel?: number;
    state?: TrainingDefinitionDTO.StateEnum;
    title?: string;
}
export namespace TrainingDefinitionDTO {
    export type StateEnum = 'PRIVATED' | 'RELEASED' | 'ARCHIVED' | 'UNRELEASED';
    export const StateEnum = {
        PRIVATED: 'PRIVATED' as StateEnum,
        RELEASED: 'RELEASED' as StateEnum,
        ARCHIVED: 'ARCHIVED' as StateEnum,
        UNRELEASED: 'UNRELEASED' as StateEnum
    }
}
