/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainingDefinitionDTO } from './trainingDefinitionDTO';
import { UserRefDTO } from './userRefDTO';
import {BasicLevelInfoDTO} from "./basicLevelInfoDTO";
import {AuthorRefDTO} from "./authorRefDTO";
import {SandboxDefinitionRefDTO} from "./sandboxDefinitionRefDTO";


/**
 * Training Instance to create.
 */
export interface TrainingInstanceCreateDTO {
    end_time?: Date;
    keyword?: string;
    organizers?: Array<UserRefDTO>;
    pool_size?: number;
    start_time?: Date;
    title?: string;
    training_definition?: TrainingDefinitionDTO;
}

export class TrainingInstanceCreateDTOClass implements TrainingInstanceCreateDTO {
  end_time: Date;
  keyword: string;
  organizers: Array<UserRefDTO>;
  pool_size: number;
  start_time: Date;
  title: string;
  training_definition: TrainingDefinitionDTO;
}
