/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Training Instance to create.
 */
export interface TrainingInstanceCreateDTO {
    endTime?: Date;
    keyword?: string;
    poolSize?: number;
    startTime?: Date;
    title?: string;
}

export class TrainingInstanceCreateDTO implements TrainingInstanceCreateDTO{

}
