/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class UserRefDTO {
    full_name: string;
    login?: string;
    user_ref_id: number;
    given_name: string;
    family_name: string;
    iss: string;
}
