import {UserRoleEnum} from "../../enums/user-role.enum";
import {Set} from 'typescript-collections/'

/**
 * Object representing user in a system. User has unique id generated by backend, name and set of roles.
 */
export class User {
  id: number;
  name: string;
  roles: Set<UserRoleEnum>;


  constructor(id: number, name: string, roles: Set<UserRoleEnum>) {
    this.id = id;
    this.name = name;
    this.roles = roles;
  }

  toString(): string {
    return this.name;
  }
}
