/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HintDTO } from './hintDTO';
import {AbstractLevelDTO} from "../abstractLevelDTO";
import {PostHookDTO} from "../../training-definition/postHookDTO";
import {PreHookDTO} from "../../training-definition/preHookDTO";


/**
 * Game Level to update.
 */
export interface GameLevelUpdateDTO extends AbstractLevelDTO{
  attachments?: Array<string>;
  content?: string;
  estimated_duration?: number;
  flag?: string;
  hints?: Array<HintDTO>;
  incorrect_flag_limit?: number;
  solution?: string;
  solution_penalized?: boolean;
}

export class GameLevelUpdateDTOClass implements GameLevelUpdateDTO {
  attachments: Array<string>;
  content: string;
  estimated_duration: number;
  flag: string;
  hints: Array<HintDTO>;
  id: number;
  incorrect_flag_limit: number;
  level_type: AbstractLevelDTO.LevelTypeEnum;
  max_score: number;
  next_level: number;
  post_hook: PostHookDTO;
  pre_hook: PreHookDTO;
  solution: string;
  solution_penalized: boolean;
  title: string;

}
