/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Paginated {
    /**
     * Page number.
     */
    number?: number;
    /**
     * Number of elements in page.
     */
    number_of_elements?: number;
    /**
     * Page size.
     */
    size?: number;
    /**
     * Total number of elements in this resource (in all Pages).
     */
    total_elements?: number;
    /**
     * Total number of pages.
     */
    total_pages?: number;
}
