/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractLevelDTO } from '../level/abstractLevelDTO';
import { BasicLevelInfoDTO } from '../level/basicLevelInfoDTO';


/**
 * .
 */
export interface AccessTrainingRunDTO {
    abstract_level_dto?: AbstractLevelDTO;
    info_about_levels?: Array<BasicLevelInfoDTO>;
    training_run_id: number;
    sandbox_instance_id: number;
    show_stepper_bar: boolean;
    start_time: Date;
}
