name: Training portal CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm_action:
        description: "Type 'yes' if you want to publish and create a new tag"
        required: true
        default: "no"

jobs:
  get_current_version:
    uses: cyberrangecz/actions-templates/.github/workflows/get_version.yml@master
    with:
      file_path: "package.json"

  codeStyle:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'

      - name: Copy .npmrc for authentication
        run: echo "${{ secrets.SENTINEL_PULL }}" >> .npmrc

      - name: Install dependencies
        run: npm ci --prefer-offline --ignore-scripts

      - name: Run Lint
        run: npm run lint

  unitTests:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    container:
      image: ${{ vars.CONTAINER_IMAGE }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'

      - name: Copy .npmrc for authentication
        run: echo "${{ secrets.SENTINEL_PULL }}" >> .npmrc

      - name: Install dependencies
        run: npm ci --prefer-offline --ignore-scripts

      - name: Run tests
        run: npm run ci-test

  build_container:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    needs: [codeStyle, unitTests, get_current_version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy .npmrc for authentication
        run: echo "${{ secrets.SENTINEL_PULL }}" >> .npmrc

      - name: Build and push Docker image
        env:
          IMAGE_NAME: "training-portal"
          IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && format('{0}', needs.get_current_version.outputs.version ) || format('{0}-dev', needs.get_current_version.outputs.version) }}
          PROD_VAL: ${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}
        uses: docker/build-push-action@v6
        with:
          context: .  # Path to the Dockerfile
          file: ./Dockerfile
          build-args: |
            PROD=${{ env.PROD_VAL }}
            --snapshotMode=redo
            --single-snapshot
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  # Controls if version consistent with semver and higner than last git tag.
  control_tag:
    if: ( github.event.pull_request.base.ref == 'master' || github.ref == 'refs/heads/master' )
    needs: get_current_version
    uses: cyberrangecz/actions-templates/.github/workflows/tag_control_template.yml@master
    with:
      VERSION: ${{ needs.get_current_version.outputs.version }}

  # Push tag only from manual workflow_dispatch with confirmed tag creation
  push_tag:
    needs: [get_current_version, control_tag, build_container]
    uses: cyberrangecz/actions-templates/.github/workflows/tag_push_template.yml@master
    with:
      VERSION: ${{ needs.get_current_version.outputs.version }}

